version: 2
jobs:
  test:
    working_directory: ~/engage_backend_service
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-compose build
      # Not using -d since will exit after completion
      # Have to figure out how to shut down redis from entrypoint script
      - run:
          name: Check test and upload if succeeded
          command: |
            scripts/test.sh
      - store_test_results:
          path: ~/engage_backend_service/tmp/test-results
      - store_artifacts:
          path: ~/engage_backend_service/tmp/test-results
          destination: tr1
  deploy_container:
    working_directory: ~/engage_backend_service
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker-compose build
      # Not using -d since will exit after completion
      # Have to figure out how to shut down redis from entrypoint script
      - run:
          name: Check test and upload if succeeded
          command: |
            scripts/test_and_deploy.sh
      - store_test_results:
          path: ~/engage_backend_service/tmp/test-results
      - store_artifacts:
          path: ~/engage_backend_service/tmp/test-results
          destination: tr1
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:9f:48:96:a1:76:08:e3:f9:5b:2e:c1:1e:5b:06:5a"
      - run:
          name: Deploy over SSH
          command: |
            ssh -f $SSH_USER@$SSH_HOST "./deploy-docker.sh"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - deploy_container:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - deploy_container
          filters:
            branches:
              only: master
